const phrases = [
    'Hallo, wêreld!',
    'Ola mundo!',
    'Shani Mwechalo!',
    'Zdravo Svijete!',
    'Ahoj Světe!',
    'Kaixo mundua!',
    'Bok Svijete!',
    'Hej, Verden!',
    'Hallo, wereld!',
    'Hello World!',
    'Saluton mondo!',
    'Hola món!',
    'Tere maailm!',
    'Hei maailma!',
    'Salut le Monde!',
    'Hallo, wrâld!',
    '¡Hola mundo!',
    'Hallo Welt!',
    'Aloha Honua!',
    'Helló világ!',
    'Halló heimur!',
    'Halo Dunia!',
    'Ciao Mondo!',
    'Habari dunia!',
    'Niatia thi!',
    'Sveika, Pasaule!',
    'Moien Welt!',
    'Hallo verden!',
    'Witaj świecie!',
    'Olá, mundo!',
    'Salut lume!',
    'Zdravo Svete!',
    'Ahoj, svet!',
    'Hejsan världen!',
    'Kamusta mundo!',
    'Merhaba Dünya!',
    'S\'mae byd!'
]

export default phrases;