/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';


export namespace Components {

  interface AppFooter {}
  interface AppFooterAttributes extends StencilHTMLAttributes {}

  interface AppHeader {}
  interface AppHeaderAttributes extends StencilHTMLAttributes {}

  interface AppHero {}
  interface AppHeroAttributes extends StencilHTMLAttributes {}

  interface AppLanguageController {
    'changeLanguage': (value: string) => void;
    'toggle': () => void;
  }
  interface AppLanguageControllerAttributes extends StencilHTMLAttributes {}

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface AppTerm {
    'def': string;
  }
  interface AppTermAttributes extends StencilHTMLAttributes {
    'def'?: string;
  }

  interface ExplorerDir {
    'label': string;
  }
  interface ExplorerDirAttributes extends StencilHTMLAttributes {
    'label'?: string;
  }

  interface ExplorerEditor {
    'annotations': { [key: string]: string };
    'content': string;
    'filename': string;
  }
  interface ExplorerEditorAttributes extends StencilHTMLAttributes {
    'annotations'?: { [key: string]: string };
    'content'?: string;
    'filename'?: string;
  }

  interface ExplorerFile {
    'close': () => void;
    'label': string;
    'open': boolean;
  }
  interface ExplorerFileAttributes extends StencilHTMLAttributes {
    'label'?: string;
    'onOpen'?: (event: CustomEvent<string>) => void;
    'open'?: boolean;
  }

  interface ExplorerSidebar {
    'addChild': (label: any, element: any) => void;
    'label': any;
  }
  interface ExplorerSidebarAttributes extends StencilHTMLAttributes {
    'label'?: any;
    'onFileOpen'?: (event: CustomEvent<any>) => void;
  }

  interface HomeFeature {}
  interface HomeFeatureAttributes extends StencilHTMLAttributes {}

  interface HomeHero {}
  interface HomeHeroAttributes extends StencilHTMLAttributes {}

  interface PageHome {}
  interface PageHomeAttributes extends StencilHTMLAttributes {}

  interface HomeSectionExample {}
  interface HomeSectionExampleAttributes extends StencilHTMLAttributes {}

  interface HomeSectionExplorer {}
  interface HomeSectionExplorerAttributes extends StencilHTMLAttributes {}

  interface HomeSectionInstall {}
  interface HomeSectionInstallAttributes extends StencilHTMLAttributes {}

  interface HomeSectionIntro {}
  interface HomeSectionIntroAttributes extends StencilHTMLAttributes {}

  interface HomeSectionStats {}
  interface HomeSectionStatsAttributes extends StencilHTMLAttributes {}

  interface HomeSection {
    'center': boolean;
    'threeUp': boolean;
    'twoUp': boolean;
  }
  interface HomeSectionAttributes extends StencilHTMLAttributes {
    'center'?: boolean;
    'threeUp'?: boolean;
    'twoUp'?: boolean;
  }

  interface NotFoundHero {}
  interface NotFoundHeroAttributes extends StencilHTMLAttributes {}

  interface PageNotFound {}
  interface PageNotFoundAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppFooter': Components.AppFooter;
    'AppHeader': Components.AppHeader;
    'AppHero': Components.AppHero;
    'AppLanguageController': Components.AppLanguageController;
    'AppRoot': Components.AppRoot;
    'AppTerm': Components.AppTerm;
    'ExplorerDir': Components.ExplorerDir;
    'ExplorerEditor': Components.ExplorerEditor;
    'ExplorerFile': Components.ExplorerFile;
    'ExplorerSidebar': Components.ExplorerSidebar;
    'HomeFeature': Components.HomeFeature;
    'HomeHero': Components.HomeHero;
    'PageHome': Components.PageHome;
    'HomeSectionExample': Components.HomeSectionExample;
    'HomeSectionExplorer': Components.HomeSectionExplorer;
    'HomeSectionInstall': Components.HomeSectionInstall;
    'HomeSectionIntro': Components.HomeSectionIntro;
    'HomeSectionStats': Components.HomeSectionStats;
    'HomeSection': Components.HomeSection;
    'NotFoundHero': Components.NotFoundHero;
    'PageNotFound': Components.PageNotFound;
  }

  interface StencilIntrinsicElements {
    'app-footer': Components.AppFooterAttributes;
    'app-header': Components.AppHeaderAttributes;
    'app-hero': Components.AppHeroAttributes;
    'app-language-controller': Components.AppLanguageControllerAttributes;
    'app-root': Components.AppRootAttributes;
    'app-term': Components.AppTermAttributes;
    'explorer-dir': Components.ExplorerDirAttributes;
    'explorer-editor': Components.ExplorerEditorAttributes;
    'explorer-file': Components.ExplorerFileAttributes;
    'explorer-sidebar': Components.ExplorerSidebarAttributes;
    'home-feature': Components.HomeFeatureAttributes;
    'home-hero': Components.HomeHeroAttributes;
    'page-home': Components.PageHomeAttributes;
    'home-section-example': Components.HomeSectionExampleAttributes;
    'home-section-explorer': Components.HomeSectionExplorerAttributes;
    'home-section-install': Components.HomeSectionInstallAttributes;
    'home-section-intro': Components.HomeSectionIntroAttributes;
    'home-section-stats': Components.HomeSectionStatsAttributes;
    'home-section': Components.HomeSectionAttributes;
    'not-found-hero': Components.NotFoundHeroAttributes;
    'page-not-found': Components.PageNotFoundAttributes;
  }


  interface HTMLAppFooterElement extends Components.AppFooter, HTMLStencilElement {}
  var HTMLAppFooterElement: {
    prototype: HTMLAppFooterElement;
    new (): HTMLAppFooterElement;
  };

  interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {}
  var HTMLAppHeaderElement: {
    prototype: HTMLAppHeaderElement;
    new (): HTMLAppHeaderElement;
  };

  interface HTMLAppHeroElement extends Components.AppHero, HTMLStencilElement {}
  var HTMLAppHeroElement: {
    prototype: HTMLAppHeroElement;
    new (): HTMLAppHeroElement;
  };

  interface HTMLAppLanguageControllerElement extends Components.AppLanguageController, HTMLStencilElement {}
  var HTMLAppLanguageControllerElement: {
    prototype: HTMLAppLanguageControllerElement;
    new (): HTMLAppLanguageControllerElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAppTermElement extends Components.AppTerm, HTMLStencilElement {}
  var HTMLAppTermElement: {
    prototype: HTMLAppTermElement;
    new (): HTMLAppTermElement;
  };

  interface HTMLExplorerDirElement extends Components.ExplorerDir, HTMLStencilElement {}
  var HTMLExplorerDirElement: {
    prototype: HTMLExplorerDirElement;
    new (): HTMLExplorerDirElement;
  };

  interface HTMLExplorerEditorElement extends Components.ExplorerEditor, HTMLStencilElement {}
  var HTMLExplorerEditorElement: {
    prototype: HTMLExplorerEditorElement;
    new (): HTMLExplorerEditorElement;
  };

  interface HTMLExplorerFileElement extends Components.ExplorerFile, HTMLStencilElement {}
  var HTMLExplorerFileElement: {
    prototype: HTMLExplorerFileElement;
    new (): HTMLExplorerFileElement;
  };

  interface HTMLExplorerSidebarElement extends Components.ExplorerSidebar, HTMLStencilElement {}
  var HTMLExplorerSidebarElement: {
    prototype: HTMLExplorerSidebarElement;
    new (): HTMLExplorerSidebarElement;
  };

  interface HTMLHomeFeatureElement extends Components.HomeFeature, HTMLStencilElement {}
  var HTMLHomeFeatureElement: {
    prototype: HTMLHomeFeatureElement;
    new (): HTMLHomeFeatureElement;
  };

  interface HTMLHomeHeroElement extends Components.HomeHero, HTMLStencilElement {}
  var HTMLHomeHeroElement: {
    prototype: HTMLHomeHeroElement;
    new (): HTMLHomeHeroElement;
  };

  interface HTMLPageHomeElement extends Components.PageHome, HTMLStencilElement {}
  var HTMLPageHomeElement: {
    prototype: HTMLPageHomeElement;
    new (): HTMLPageHomeElement;
  };

  interface HTMLHomeSectionExampleElement extends Components.HomeSectionExample, HTMLStencilElement {}
  var HTMLHomeSectionExampleElement: {
    prototype: HTMLHomeSectionExampleElement;
    new (): HTMLHomeSectionExampleElement;
  };

  interface HTMLHomeSectionExplorerElement extends Components.HomeSectionExplorer, HTMLStencilElement {}
  var HTMLHomeSectionExplorerElement: {
    prototype: HTMLHomeSectionExplorerElement;
    new (): HTMLHomeSectionExplorerElement;
  };

  interface HTMLHomeSectionInstallElement extends Components.HomeSectionInstall, HTMLStencilElement {}
  var HTMLHomeSectionInstallElement: {
    prototype: HTMLHomeSectionInstallElement;
    new (): HTMLHomeSectionInstallElement;
  };

  interface HTMLHomeSectionIntroElement extends Components.HomeSectionIntro, HTMLStencilElement {}
  var HTMLHomeSectionIntroElement: {
    prototype: HTMLHomeSectionIntroElement;
    new (): HTMLHomeSectionIntroElement;
  };

  interface HTMLHomeSectionStatsElement extends Components.HomeSectionStats, HTMLStencilElement {}
  var HTMLHomeSectionStatsElement: {
    prototype: HTMLHomeSectionStatsElement;
    new (): HTMLHomeSectionStatsElement;
  };

  interface HTMLHomeSectionElement extends Components.HomeSection, HTMLStencilElement {}
  var HTMLHomeSectionElement: {
    prototype: HTMLHomeSectionElement;
    new (): HTMLHomeSectionElement;
  };

  interface HTMLNotFoundHeroElement extends Components.NotFoundHero, HTMLStencilElement {}
  var HTMLNotFoundHeroElement: {
    prototype: HTMLNotFoundHeroElement;
    new (): HTMLNotFoundHeroElement;
  };

  interface HTMLPageNotFoundElement extends Components.PageNotFound, HTMLStencilElement {}
  var HTMLPageNotFoundElement: {
    prototype: HTMLPageNotFoundElement;
    new (): HTMLPageNotFoundElement;
  };

  interface HTMLElementTagNameMap {
    'app-footer': HTMLAppFooterElement
    'app-header': HTMLAppHeaderElement
    'app-hero': HTMLAppHeroElement
    'app-language-controller': HTMLAppLanguageControllerElement
    'app-root': HTMLAppRootElement
    'app-term': HTMLAppTermElement
    'explorer-dir': HTMLExplorerDirElement
    'explorer-editor': HTMLExplorerEditorElement
    'explorer-file': HTMLExplorerFileElement
    'explorer-sidebar': HTMLExplorerSidebarElement
    'home-feature': HTMLHomeFeatureElement
    'home-hero': HTMLHomeHeroElement
    'page-home': HTMLPageHomeElement
    'home-section-example': HTMLHomeSectionExampleElement
    'home-section-explorer': HTMLHomeSectionExplorerElement
    'home-section-install': HTMLHomeSectionInstallElement
    'home-section-intro': HTMLHomeSectionIntroElement
    'home-section-stats': HTMLHomeSectionStatsElement
    'home-section': HTMLHomeSectionElement
    'not-found-hero': HTMLNotFoundHeroElement
    'page-not-found': HTMLPageNotFoundElement
  }

  interface ElementTagNameMap {
    'app-footer': HTMLAppFooterElement;
    'app-header': HTMLAppHeaderElement;
    'app-hero': HTMLAppHeroElement;
    'app-language-controller': HTMLAppLanguageControllerElement;
    'app-root': HTMLAppRootElement;
    'app-term': HTMLAppTermElement;
    'explorer-dir': HTMLExplorerDirElement;
    'explorer-editor': HTMLExplorerEditorElement;
    'explorer-file': HTMLExplorerFileElement;
    'explorer-sidebar': HTMLExplorerSidebarElement;
    'home-feature': HTMLHomeFeatureElement;
    'home-hero': HTMLHomeHeroElement;
    'page-home': HTMLPageHomeElement;
    'home-section-example': HTMLHomeSectionExampleElement;
    'home-section-explorer': HTMLHomeSectionExplorerElement;
    'home-section-install': HTMLHomeSectionInstallElement;
    'home-section-intro': HTMLHomeSectionIntroElement;
    'home-section-stats': HTMLHomeSectionStatsElement;
    'home-section': HTMLHomeSectionElement;
    'not-found-hero': HTMLNotFoundHeroElement;
    'page-not-found': HTMLPageNotFoundElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
